twitter: ""
github: ""
linkedin: ""
youtube: "https://www.youtube.com/@jaredforthmusic"
dribbble: ""
instagram: ""
facebook: ""
medium: "https://medium.com/jazz-theory"
patreon: ""
paypal: ""
unsplash: ""
