twitter: ""
github: ""
linkedin: ""
youtube: "https://www.youtube.com/@jaredforthmusic"
dribbble: ""
instagram: "https://instagram.com/jaredforthmusi"
facebook: ""
medium: "https://medium.com/jazz-theory"
patreon: ""
paypal: "https://paypal.me/jaredforthmusic"
unsplash: ""
